---
- hosts: localhost
  connection: local

  tasks:
    - name: Set up terminal and CLI
      include: tasks/cli.yml

    - name: Install apps via cask
      include: tasks/apps.yml

    - name: Set OSX defaults
      include: tasks/osx.yml

