---
- hosts: localhost
  connection: local
  vars:
    OS: "{{ 'osx' if ansible_os_family == 'Darwin' else 'linux' }}"
  vars_files:
    - ./vars/{{ ansible_distribution }}.yml

  roles:
    - base

  tasks:
    - debug: msg={{ PACKAGES }}
    - name: install packages
      include: ./tasks/{{ OS }}_packages.yml

    - name: install apps
      include: ./tasks/{{ OS }}_apps.yml

