---
- name: tap thoughtbot homebrew formulae
  homebrew_tap: tap=thoughtbot/formulae

- name: install languages
  homebrew: name={{item}} state=present
  with_items:
    - python
    - rbenv

- name: install vim
  homebrew: name=vim state=present install_options=override-system-vi

- name: install the rest of the cli packages
  homebrew: name={{item}} state=present
  with_items:
    - git-crypt
    - zsh
    - tmux
    - reattach-to-user-namespace
    - rcm
    - ag
    - z

- name: check out dotfiles
  git:
    repo: https://github.com/sw00/dotfiles.git
    dest: /Users/{{ansible_user_id}}/dotfiles
    depth: 1
    update: yes

- name: install dotfiles
  shell: rcup -d /Users/{{ansible_user_id}}/dotfiles
  args:
    chdir: /Users/{{ansible_user_id}}/dotfiles

- name: change default shell to zsh
  user: name={{ansible_user_id}} shell=/usr/local/bin/zsh
  become: yes
