---
- name: tap brew-cask
  homebrew_tap: tap=caskroom/cask

- name: tap alternate versions
  homebrew_tap: tap=caskroom/versions

- name: install cask apps
  homebrew_cask: 
    name: "{{ item }}"
  with_items: "{{ APPS }}"

