---
# -------------- Input Devices ---------------------
- name: repeat keys instead of press-and-hold
  osx_defaults: 
    key: ApplePressAndHoldEnabled
    type: bool
    value: false

- name: set fastest key repeat rate
  osx_defaults:
    key: KeyRepeat
    type: int
    value: 1

- name: set delay before keys repeat (ms)
  osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: 15

- name: disable annoying autocorrect
  osx_defaults: 
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

- name: use standard function keys
  osx_defaults:
    key: com.apple.keyboard.fnState
    type: bool
    value: true

- name: enable tap to click
  osx_defaults:
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1

# - name: map caps lock to ctrl
#   script: files/caps-to-ctrl.sh

# -------------- Dock ---------------------
- name: automatically hide the dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: position dock on the left
  osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left

- name: only display some apps permanently
  osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    type: array
    value: ["Finder", "Chrome", "iTerm2"]

- name: dim hidden apps
  osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: true

- name: enable dashboard
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: false

- name: don't show dashboard as space
  osx_defaults:
    domain: com.apple.dashboard
    key: dashboard-in-overlay
    type: bool
    value: true

- name: enable dashboard on top-left hot corner
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: 7

- name: don't use modifier key for hot corner
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-modifier
    type: int
    value: 0

# -------------- Screensaver ---------------------

- name: prompt for password when screensaver activates
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1

- name: immediately activate password prompt when screensaver activates
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: 0.0

# -------------- Other ---------------------
- name: stop creating .DS_Store files
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: false
