---
- name: install yaourt
  pacman: name=yaourt state=present
  become: yes
  when: package_manager == 'pacman'

- name: install rcm
  command: yaourt -S --noconfirm rcm 
  args:
    creates: /usr/bin/rcup
  when: package_manager == 'pacman'

- name: install zsh
  pacman: name=zsh state=present
  become: yes
  when: package_manager == 'pacman'

