---
- name: install dependencies
  include: "{{ OS }}.yml"
  vars:
    package_manager: "{{ package_managers[ansible_distribution] }}"

- name: check out dotfiles
  git:
    repo: https://github.com/sw00/dotfiles.git
    dest: "{{ ansible_env.HOME }}/dotfiles"
    depth: 1
    update: yes

- name: install dotfiles
  shell: rcup -d {{ ansible_env.HOME }}/dotfiles
  args:
    chdir: "{{ ansible_env.HOME }}/dotfiles"

- name: change default shell to zsh
  user: 
    name: "{{ ansible_user_id }}" 
    shell: "{{ '/usr/bin/zsh' if OS != 'osx' else '/bin/zsh' }}"
  become: yes
